### ISSUE TITLE
东莞、

### ISSUE THREAD

**Issue by KennyWho** [qq1037861239/bilibiliCacheVideosConvert#4]
一条野狗

**Comment by qq1037861239** [comment]
> 你把公司 电话 地址 都放上 我看看你牛逼，还是我牛逼。我就都放着给你，让你来 行吗，小臂崽子 是不是在网上猖狂管了？ 扣字挺几把厉害？就你那几个小几把语言琢磨一天了？是不是觉得自己明白了？看你写那个几把玩意，是不是菜逼找不到工作，赚那点B钱够给你妈买坟吗。知道西安公墓多钱吗？是不是给你妈埋他妈野坟呢

贱种，你个垃圾就只顾着b上爽    来    把你亲妈地址给我呀

**Comment by qq1037861239** [comment]
> 你把公司 电话 地址 都放上 我看看你牛逼，还是我牛逼。我就都放着给你，让你来 行吗，小臂崽子 是不是在网上猖狂管了？ 扣字挺几把厉害？就你那几个小几把语言琢磨一天了？是不是觉得自己明白了？看你写那个几把玩意，是不是菜逼找不到工作，赚那点B钱够给你妈买坟吗。知道西安公墓多钱吗？是不是给你妈埋他妈野坟呢

关键是我不知道你亲妈只喜欢外国几把呢还是不挑食不捡食

**Comment by KennyWho** [comment]
弟弟 你怎么光要呢 我给你电话 你把你的也发来 看你敢不敢打过来

**Comment by KennyWho** [comment]
QQ 你都不敢加 你跟我BB 你妈臭逼呢 啊 键盘侠？草你妈的 气死你得了 你妈的臭B养你妈的臭鱼烂虾

**Comment by KennyWho** [comment]
先加QQ 吧 弟弟 你可别跟我在这BB了 ，我有点可怜你，网上叫的贼凶。

**Comment by dcy0701** [comment]
@qq1037861239 加人家qq呗  瞅你那怂样

**Comment by qq1037861239** [comment]
> @qq1037861239 加人家qq呗 瞅你那怂样

你们这都些什么垃圾玩意，Apollo11下的高贵素质呢？还是说装个b而已，骨子里本来就是乐色
